cache:
  pipeline: [~/.npm]

shared:
  image: node:14

jobs:
  main:
    annotations:
      screwdriver.cd/ram: TURBO
      screwdriver.cd/cpu: TURBO
    steps:
      - install-chrome: ./build-scripts/setup-chrome.sh
      - install-ember-cli: npm install -g ember-cli
      - cd-to-parent: cd ..
      - new-addon: ember addon testme --yarn
      - cd-to-addon: cd testme
      - ember-try: yarn run test:ember-compatibility
      # - install: yarn install --frozen-lockfile
      # - test: yarn test
    requires:
      - ~pr
      - ~commit

  publish:
    requires: main
    steps:
      - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git /tmp/ci
      - publish: |
          . /tmp/ci/git-ssh.sh
          npx semantic-release
    secrets:
      - NPM_TOKEN
      - GH_TOKEN
      - GIT_KEY_BASE64
